service: serverless-webpack-multiple-entries-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3

custom:
  includePackages:  # packages to be included in distribution
    - fbgraph   

functions:
  first:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: first
